name: gtex-link-dev

services:
  gtex_link_api_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: gtex-link-api-dev
    ports:
      - "${API_PORT_HOST:-8002}:8000"  # Use 8002 to avoid conflicts with phentrieve (8001)
    environment:
      - GTEX_LINK_HOST=0.0.0.0
      - GTEX_LINK_PORT=8000
      - GTEX_LINK_TRANSPORT_MODE=http
      - GTEX_LINK_MCP_PATH=/mcp
      - GTEX_LINK_LOG_LEVEL=DEBUG
      - GTEX_LINK_LOG_FORMAT=console
      - GTEX_LINK_RELOAD=true
      # Development CORS settings (more permissive)
      - GTEX_LINK_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000","http://localhost:8002","*"]
      - GTEX_LINK_CORS_ALLOW_CREDENTIALS=true
    volumes:
      # Mount source code for development (read-write for hot reload)
      - ../gtex_link:/app/gtex_link
      - ../tests:/app/tests
      - ../server.py:/app/server.py
      - ../mcp_server.py:/app/mcp_server.py
      - ../mcp_http_server.py:/app/mcp_http_server.py
    command: ["/app/.venv/bin/python", "server.py"]
    restart: unless-stopped
    networks:
      - gtex_link_dev_network

networks:
  gtex_link_dev_network:
    driver: bridge
    name: gtex_link_dev_network
