# Production docker-compose override
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  gtex-link:
    # Production-specific environment variables
    environment:
      GTEX_LINK_LOG_LEVEL: INFO
      GTEX_LINK_LOG_FORMAT: json
      GTEX_LINK_RELOAD: "false"
      GTEX_LINK_CACHE_SIZE: 2000
      GTEX_LINK_CACHE_TTL: 7200
      GTEX_LINK_API_RATE_LIMIT_PER_SECOND: 5.0
    
    # Remove development volume mounts
    volumes: []
    
    # Use the production command
    command: ["gtex-link", "server", "--host", "0.0.0.0", "--port", "8000"]
    
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      
      # Production restart policy
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Enhanced health check for production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    # Production logging with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        labels: "service=gtex-link,environment=production"